spring:
  application:
    name: spring-cloud-api-gateway-service
#  cloud:
#    gateway:
#      routes:
#        -id: stock-inquiry
#        uri: http://localhost:8700/
#        predicates:
#          -Path=/apis/v1/product-inquiry/**



server:
  port: 8900
